; Exercise 1.14.  Draw the tree illustrating the process
; generated by the count-change procedure of section 1.2.2
; in making change for 11 cents. What are the orders of growth
; of the space and number of steps used by this process as
; the amount to be changed increases?


; For reference:

(define (count-change amount)
  (cc amount 5))
(define (cc amount kinds-of-coins)
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-coins 1))
                 (cc (- amount
                        (first-denomination kinds-of-coins))
                     kinds-of-coins)))))
(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))


; Drew this on paper, since it would take forever to format
; properly in a text editor.

; What are the orders of growth of the space?
; O(n). We need to keep track of deferred operations (summing the amounts).
; The longest chain of deferred operations exists on the branch of the
; tree where we compute the total using only pennies.
; This branch is about n~deep.

; What are the orders of growth of the number of steps?
; O(n^(number of coins)).




